version: "3.9"

services:
  redis1:
    image: redis:7-alpine
    container_name: redis1
    ports:
      - "7001:6379"

  redis2:
    image: redis:7-alpine
    container_name: redis2
    ports:
      - "7002:6379"

  redis3:
    image: redis:7-alpine
    container_name: redis3
    ports:
      - "7003:6379"

  redis4:
    image: redis:7-alpine
    container_name: redis4
    ports:
      - "7004:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
    environment:
      - JAVA_OPTS=-Xmx1g
