version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - JAVA_OPTS=-Xmx1g

  tests:
    build:
      context: .
      target: tests
    command: mvn test
